# Generated by Django 5.2.8 on 2025-11-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
        migrations.AddField(
            model_name='form',
            name='seo_content',
            field=models.TextField(blank=True, help_text='Shown under the form (you can include headings, paragraphs, links, etc.)', verbose_name='On-page SEO Content (HTML allowed)'),
        ),
        migrations.AddField(
            model_name='form',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Appears in Google snippet under the title.', verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='form',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Appears in browser tab and Google search results.', max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='form',
            name='fields_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='form',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='forms/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
