# Generated by Django 5.2.8 on 2025-11-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_form_description_form_seo_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='seo_content',
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='form',
            name='seo_ctas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='form',
            name='seo_faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='form',
            name='seo_h1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='seo_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='form',
            name='seo_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='form',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='forms/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
