# Generated by Django 5.2.8 on 2025-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_form_seo_content_form_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='total_pages',
            field=models.IntegerField(default=1),
        ),
    ]
