# Generated by Django 5.2.8 on 2025-11-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_form_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='seo_ctas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='form',
            name='seo_faqs',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
