# Generated by Django 5.2.8 on 2025-11-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_form_seo_ctas_alter_form_seo_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='seo_faqs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
